### PR TITLE
Fix instructions for building on openSUSE

### PR DESCRIPTION
**Pull request by binary-sequence**

### CODE REVIEW

**Comment by jmaynard** [comment]
I'm guessing that the `-t pattern` option on the packages doesn't do anything?

**Comment by binary-sequence** [comment]
It does when it is a pattern, the only pattern there is `devel_basis`

**Comment by binary-sequence** [comment]
If it is not a pattern, and `-t pattern` is used, the zypper command fails with "pattern not found"

**Comment by jmaynard** [comment]
I thought it might be something like that. OK, looks good to me.

**Review by jmaynard — APPROVED** [review]

**Pull request merged**
